<br>

<br>

# Stanford Open Policing Project

<br>

Hello everyone ! 

In this notebook, we are going to do an exploratory data analysis.

Let's start with importing the libraries we might need.

<br>

In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from collections import Counter
import warnings
warnings.filterwarnings('ignore')

<br>

After importing the libraries next step is reading the file.

<br>

In [2]:
df = pd.read_csv("police_project.csv")

<br>
To make an efficient analysis, It is very crucial to get familiar with the dataset.
<br> <br>

In [3]:
df.shape

(91741, 15)

<br>
I personally prefer to get a sample randomly from the dataset instead of getting some data from the top so I can see if there is something strange.
<br><br>

In [4]:
df.sample(5)

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
41870,2010-04-22,06:51,NaN,M,1968.0,42.0,White,Speeding,Speeding,False,NaN,Citation,False,16-30 Min,False
66395,2013-01-16,01:12,NaN,M,1990.0,23.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
62228,2012-07-25,12:16,NaN,M,1989.0,23.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
90526,2015-11-02,18:56,NaN,M,1988.0,27.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
39090,2009-12-17,01:11,NaN,M,1967.0,42.0,Black,Special Detail/Directed Patrol,Other,False,NaN,Citation,False,0-15 Min,False

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91741 entries, 0 to 91740
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           91741 non-null  object
 1   stop_time           91741 non-null  object
 2   county_name         0 non-null      float64
 3   driver_gender       86406 non-null  object
 4   driver_age_raw      86414 non-null  float64
 5   driver_age          86120 non-null  float64
 6   driver_race         86408 non-null  object
 7   violation_raw       86408 non-null  object
 8   violation           86408 non-null  object
 9   search_conducted    91741 non-null  bool
 10  search_type         3196 non-null   object
 11  stop_outcome        86408 non-null  object
 12  is_arrested         86408 non-null  object
 13  stop_duration       86408 non-null  object
 14  drugs_related_stop  91741 non-null  bool
dtypes: bool(2), float64(3), object(10)
memory usage: 9.3+ MB

<br>
There are some info about the dataset right above. <br><br>

- According to that we have some columns which consist of null values in and some columns which almost don't have any non-null value in. It would be benefical to get rid of those columns when we start cleaning out data.
<br><br>
- Also another thing that draw my attention is there are some columns includes date-time but their data type is object which doesn't help and some columns which have numeric values but their data type are object too. 
<br><br>

I always make a 'To Do List' before start cleaning the data. Thus I do not forget or skip any step during cleaning.

- I am going to explore every column one by one to make sure there is nothing important that I do not notice. 
<br>

- Then as a next step with the results I will make my 'To Do List'.
<br>
- One more thing I would like to share is, it is very important that not working on your actual dataset to prevent undesirable incidents. Always get a copy of you dataset and work on it.

In [6]:
df1 = df.copy()

In [7]:
df1.columns

Index(['stop_date', 'stop_time', 'county_name', 'driver_gender',
       'driver_age_raw', 'driver_age', 'driver_race', 'violation_raw',
       'violation', 'search_conducted', 'search_type', 'stop_outcome',
       'is_arrested', 'stop_duration', 'drugs_related_stop'],
      dtype='object')

In [8]:
df1.isnull().sum()

stop_date                 0
stop_time                 0
county_name           91741
driver_gender          5335
driver_age_raw         5327
driver_age             5621
driver_race            5333
violation_raw          5333
violation              5333
search_conducted          0
search_type           88545
stop_outcome           5333
is_arrested            5333
stop_duration          5333
drugs_related_stop        0
dtype: int64

- As you can see, county_name column do not have any non-null value and also the search_type column almost consists of null values.

## To Do List

1. Change the dtype of stop_date and stop_time columns.
2. Drop the column county_name.
3. Driver_age_raw and Driver_age columns are the same, only one of them has more missing value. We can drop one of them.
4. It is the same for violation_raw and violation column. Better to drop one of them.
5. Search_type columns has so many missing values, we can drop it as weel.
6. is_arrested column better to be bool.

Since we have specified the steps we are going to do for the purpose of cleaning the dataset we can get going.

### Stop_date - Stop_time

In [9]:
df1['stop_date'] = pd.to_datetime(df1.stop_date)

In [10]:
df1.stop_date

0       2005-01-02
1       2005-01-18
2       2005-01-23
3       2005-02-20
4       2005-03-14
           ...
91736   2015-12-31
91737   2015-12-31
91738   2015-12-31
91739   2015-12-31
91740   2015-12-31
Name: stop_date, Length: 91741, dtype: datetime64[ns]

In [11]:
df1['stop_time'] = pd.to_datetime(df1['stop_time'], format='%H:%M').dt.hour

In [12]:
df1.stop_time

0         1
1         8
2        23
3        17
4        10
         ..
91736    20
91737    20
91738    20
91739    21
91740    22
Name: stop_time, Length: 91741, dtype: int64

<br>

### County_name

In [13]:
df1.drop('county_name',axis = 1, inplace = True)

In [14]:
df1.columns

Index(['stop_date', 'stop_time', 'driver_gender', 'driver_age_raw',
       'driver_age', 'driver_race', 'violation_raw', 'violation',
       'search_conducted', 'search_type', 'stop_outcome', 'is_arrested',
       'stop_duration', 'drugs_related_stop'],
      dtype='object')

<br>

### Driver_age_raw - Driver_age

In [15]:
df1.driver_age.isnull().sum()

5621

In [16]:
df1.driver_age_raw.isnull().sum()

5327

In [17]:
df1.stop_date.sort_values()

0       2005-01-02
1       2005-01-18
2       2005-01-23
3       2005-02-20
4       2005-03-14
           ...
91718   2015-12-31
91717   2015-12-31
91739   2015-12-31
91727   2015-12-31
91740   2015-12-31
Name: stop_date, Length: 91741, dtype: datetime64[ns]

In [18]:
df1[(df1.driver_age_raw.notnull())& (df1.driver_age.isnull())][['stop_date','driver_age_raw', 'driver_age']]

       stop_date  driver_age_raw  driver_age
146   2005-10-05             0.0         NaN
281   2005-10-10             0.0         NaN
331   2005-10-12             0.0         NaN
414   2005-10-17          2005.0         NaN
455   2005-10-18             0.0         NaN
...          ...             ...         ...
89375 2015-09-21             0.0         NaN
90330 2015-10-28             0.0         NaN
90767 2015-11-13             0.0         NaN
91378 2015-12-12             0.0         NaN
91553 2015-12-21             0.0         NaN

[294 rows x 3 columns]

<br>

- As you can see we have 0 in driver_age_raw column which is not different than Null.

<br><br>

In [19]:
df1[df1.driver_age_raw == 0].driver_age_raw.value_counts()

0.0    257
Name: driver_age_raw, dtype: int64

- I am just going to chech if there a way to fill some of them from driver_age column.

In [20]:
df1[(df1.driver_age_raw == 0) & (df1.driver_age.notnull())]

Empty DataFrame
Columns: [stop_date, stop_time, driver_gender, driver_age_raw, driver_age, driver_race, violation_raw, violation, search_conducted, search_type, stop_outcome, is_arrested, stop_duration, drugs_related_stop]
Index: []

- And I couldn't find any value to fill them up :(

In [21]:
zero_index_age_raw = df1[df1.driver_age_raw == 0].driver_age_raw.index
zero_index_age_raw

Int64Index([  146,   281,   331,   455,   748,   835,   893,  1479,  1740,
             1760,
            ...
            86728, 86968, 87944, 88262, 89115, 89375, 90330, 90767, 91378,
            91553],
           dtype='int64', length=257)

In [22]:
df1['driver_age_raw'].loc[zero_index_age_raw]= df1['driver_age_raw'].loc[zero_index_age_raw].replace(0.0,np.nan)

In [23]:
df1.loc[zero_index_age_raw].driver_age_raw

146     NaN
281     NaN
331     NaN
455     NaN
748     NaN
         ..
89375   NaN
90330   NaN
90767   NaN
91378   NaN
91553   NaN
Name: driver_age_raw, Length: 257, dtype: float64

In [24]:
df1.driver_age_raw.isnull().sum()

5584

In [28]:
df1[(df1.driver_age_raw.notnull()) & (df1.driver_age.isnull())][['stop_date','driver_age_raw', 'driver_age']]

       stop_date  driver_age_raw  driver_age
414   2005-10-17          2005.0         NaN
3758  2006-02-06          2006.0         NaN
5200  2006-03-29          1997.0         NaN
6016  2006-04-26          2006.0         NaN
7397  2006-06-12          1887.0         NaN
8373  2006-07-17          2006.0         NaN
8656  2006-07-27          2006.0         NaN
9059  2006-08-09          2006.0         NaN
9359  2006-08-22          2006.0         NaN
10023 2006-09-12          2006.0         NaN
10357 2006-09-24          2004.0         NaN
10827 2006-10-11          2002.0         NaN
12972 2006-12-21          2006.0         NaN
14890 2007-02-21          2007.0         NaN
16064 2007-04-10          2007.0         NaN
16482 2007-04-27          2007.0         NaN
17964 2007-06-17          8801.0         NaN
18143 2007-06-24          2001.0         NaN
18149 2007-06-24          2005.0         NaN
20099 2007-09-12          2003.0         NaN
22157 2007-12-06          2006.0         NaN
23262 2008-01-23          1998.0         NaN
24045 2008-02-24          2005.0         NaN
25950 2008-05-20          1997.0         NaN
26239 2008-05-29          2007.0         NaN
26437 2008-06-06          2007.0         NaN
28872 2008-09-11          2008.0         NaN
30350 2008-11-12          2008.0         NaN
31606 2009-01-09          2006.0         NaN
37738 2009-10-07          2009.0         NaN
37779 2009-10-10          2919.0         NaN
37818 2009-10-11          2004.0         NaN
39125 2009-12-18          2000.0         NaN
53160 2011-10-13          1997.0         NaN
56377 2012-02-05          2011.0         NaN
58284 2012-03-26          2009.0         NaN
66876 2013-02-04          2013.0         NaN

In [54]:
df1.drop('driver_age_raw',axis = 1, inplace = True)

<br>

### Violatin_raw - Violation

In [61]:
df1['violation_raw'].value_counts(dropna = False)

Speeding                            48463
Other Traffic Violation             16224
Equipment/Inspection Violation      11020
NaN                                  5333
Registration Violation               3432
Seatbelt Violation                   2952
Special Detail/Directed Patrol       2455
Call for Service                     1298
Violation of City/Town Ordinance      211
Motorist Assist/Courtesy              203
APB                                    79
Suspicious Person                      56
Warrant                                15
Name: violation_raw, dtype: int64

In [62]:
df1['violation'].value_counts(dropna = False)

Speeding               48463
Moving violation       16224
Equipment              11020
NaN                     5333
Other                   4317
Registration/plates     3432
Seat belt               2952
Name: violation, dtype: int64

- Even though violation column looks more orginized, I will drop violation column and reorganize violation_raw column.

In [ ]:
df1.drop('vioaltion_raw')